/* Listar nombre, cargo (tabla empleado) y DNOM (tabla departamento) al que pertenece */
SELECT EMPLEADO.NOMBRE, EMPLEADO.CARGO, DEPARTAMENTO.DNOM AS "NOMBRE DEPARTAMENTO" FROM EMPLEADO INNER JOIN DEPARTAMENTO ON EMPLEADO.DEPT_NO = DEPARTAMENTO.DEPT_NO 
ORDER BY EMPLEADO.NOMBRE ASC;

SELECT E.NOMBRE, E.CARGO, DEP.DNOM AS "NOMBRE DEPARTAMENTO" FROM EMPLEADO E NATURAL JOIN DEPARTAMENTO DEP ORDER BY E.NOMBRE ASC;

/* Devuelve un listado con los Detalles de las ventas (todos los atributos) y la Descricpión del Producto. */
SELECT DETALLE.*, PRODUCTO.DESCRIPCION FROM DETALLE INNER JOIN PRODUCTO ON DETALLE.PRODUCTO_NUMERO = PRODUCTO.PRODUCTO_NUMERO ORDER BY DETALLE.PEDIDO_NUMERO ASC;