/* Jesús Carrillo González - BBDD */

CREATE DATABASE CLINICA;

USE CLINICA;

CREATE TABLE DOCTOR(
    CODIGO VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(15) NOT NULL,
    ESPECIALIDAD VARCHAR(15) NOT NULL
);

CREATE TABLE PACIENTE(
    SS INTEGER(12) UNSIGNED PRIMARY KEY,
    NOMBRE VARCHAR(15) NOT NULL,
    EDAD TINYINT(2) UNSIGNED NOT NULL
);

CREATE TABLE UNIDAD(
    ID INTEGER(5) UNSIGNED PRIMARY KEY,
    NOMBRE VARCHAR(15) NOT NULL,
    PLANTA TINYINT(2) UNSIGNED
);

CREATE TABLE ATIENDE(
    CODIGO VARCHAR(10),
    SS INTEGER(12) UNSIGNED,
    FECHA DATE NOT NULL,
    SINTOMA VARCHAR(30) NOT NULL,
    TRATAMIENTO VARCHAR(40) NOT NULL,
    PRIMARY KEY(CODIGO, SS),
    CONSTRAINT FK_1 FOREIGN KEY (CODIGO) REFERENCES DOCTOR(CODIGO),
    CONSTRAINT FK_2 FOREIGN KEY (SS) REFERENCES PACIENTE(SS)
);

CREATE TABLE INGRESADO(
    ID INTEGER(5) UNSIGNED,
    SS INTEGER(12) UNSIGNED,
    FECHA DATE NOT NULL,
    PRIMARY KEY(ID, SS),
    CONSTRAINT FK_3 FOREIGN KEY (ID) REFERENCES UNIDAD(ID),
    CONSTRAINT FK_4 FOREIGN KEY (SS) REFERENCES PACIENTE(SS)
);