CREATE DATABASE if not EXISTS SUBASTA;

USE SUBASTA;

DROP TABLE IF EXISTS LOTE;
CREATE TABLE LOTE(
    CATNUM INTEGER(5) PRIMARY KEY,
    SALIDA DECIMAL(9,2) UNSIGNED NOT NULL,
    PUJAMAX DECIMAL(9,2) UNSIGNED NOT NULL DEFAULT 0,
    TIEMPO TIME
);

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
    USUARIO VARCHAR(15) PRIMARY KEY,
    CLAVE VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40)
);

DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE PRODUCTO(
    CODIGO INTEGER(10) PRIMARY KEY,
    NOMBRE VARCHAR(15) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    FOTO BLOB, /*Para fotos-archivos*/
    CATNUM INTEGER(5),
    CONSTRAINT FK_1 FOREIGN KEY (CATNUM) REFERENCES LOTE(CATNUM)
);

DROP TABLE IF EXISTS PUJA;
CREATE TABLE PUJA(
    CATNUM INTEGER(5),
    USUARIO VARCHAR(15),
    DIA DATE NOT NULL,
    HORA TIME NOT NULL,
    CANTIDAD DECIMAL(9,2) UNSIGNED NOT NULL,
    PRIMARY KEY(CATNUM, USUARIO),
    CONSTRAINT FK_2 FOREIGN KEY (CATNUM) REFERENCES LOTE(CATNUM),
    CONSTRAINT FK_3 FOREIGN KEY (USUARIO) REFERENCES CLIENTE(USUARIO)
);